### PR TITLE
Added Jetbrains port

### PR DESCRIPTION
**Pull request by Grafikart**

### CODE REVIEW

**Review by enkia — CHANGES_REQUESTED** [review]
I'm not very familiar with JetBrains. Can you publish this to the JetBrains repository?

Also, since it's just the Tokyo Night syntax colors, may want to change the wording a bit to be more specific?

**JetBrains**   
[Tokyo Night Color Scheme](https://github.com/Grafikart/tokyo-night-jetbrains-theme) for Night Owl / Material Night Theme

**Comment by Grafikart** [comment]
I'll see if it's easy to publish on Jetbrains repository. I'll do the change in wording this week end

**Comment by Grafikart** [comment]
@enkia sorry for the delay I just published the color scheme on Jetbrain, they need to review it manually (in the mean time I fixed the wording

**Comment by Grafikart** [comment]
It's published on jetbrains repository

**Comment by enkia** [comment]
Thanks @Grafikart for both of your contributions! I may try JetBrains again now that I know I can use my favorite theme. :)

**Pull request merged**
